"""create face_embeddings table

Revision ID: 2279c7204a5e
Revises: 7c6286a1d78a
Create Date: 2025-05-19 17:55:22.943527

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '2279c7204a5e'
down_revision = '7c6286a1d78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_embeddings',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('embedding', Vector(512), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_embeddings')
    # ### end Alembic commands ###
