"""Initial migration

Revision ID: 9942db353e76
Revises: 
Create Date: 2025-04-29 22:35:44.770417

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy 


# revision identifiers, used by Alembic.
revision = '9942db353e76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_embeddings')
    # ### end Alembic commands ###
